export default [
    {
        id: 1,
        image: 'rose.jpg',
        name: 'Three Stone Gemstone Ring',
        price: 4,
        desc: '29.2 K Glossom Three Row Double Halo with White Diamonds, white gold engagement ring.',
        quantity: 5,
        sideone: '/public/images/rose.jpg',
        sidetwo: '/public/images/third.jpg',
        sidethree: '/public/images/second.jpg',
    },
    {
        id: 2,
        image: 'fourth.jpg',
        name: 'Solitaire Knife Edge ring',
        price: 3,
        desc: '89.2 K Glossom Three Row Double Halo with White Diamonds, white gold engagement ring.',
        quantity: 5,
        sideone: '/public/images/fourth.jpg',
        sidetwo: '/public/images/third.jpg',
        sidethree: '/public/images/second.jpg',
    },
    {
        id: 3,
        image: 'third.jpg',
        name: 'Side Stone Ring in Pavé Setting',
        price: 2,
        desc: '79.2 K Glossom Three Row Double Halo with White Diamonds, white gold engagement ring.',
        quantity: 5,
        sideone: '/public/images/third.jpg',
        sidetwo: '/public/images/fourth.jpg',
        sidethree: '/public/images/second.jpg',
    },
    {
        id: 4,
        image: 'fourth.jpg',
        name: 'Side Stone Ring in Pavé Setting',
        price: 1,
        desc: '49.2 K Glossom Three Row Double Halo with White Diamonds, white gold engagement ring.',
        quantity: 5,
        sideone: '/public/images/fourth.jpg',
        sidetwo: '/public/images/fourth.jpg',
        sidethree: '/public/images/second.jpg',
        
    },
    {
        id: 5,
        image: 'rose.jpg',
        name: 'Three Stone Gemstone Ring',
        price: 4,
        desc: '9.2 K Glossom Three Row Double Halo with White Diamonds, white gold engagement ring.',
        quantity: 5,
        sideone: '/public/images/rose.jpg',
        sidetwo: '/public/images/fourth.jpg',
        sidethree: '/public/images/second.jpg',
    },
    {
        id: 6,
        image: 'second.jpg',
        name: 'Solitaire Knife Edge ring',
        price: 3,
        desc: '19.7 K Glossom Three Row Double Halo with White Diamonds, white gold engagement ring.',
        quantity: 5,
        sideone: '/public/images/second.jpg',
        sidetwo: '/public/images/fourth.jpg',
        sidethree: '/public/images/second.jpg',
    }
]